### ISSUE TITLE
Link and URL tags should _not_ be the same

### ISSUE THREAD

**Issue by lorezyra** [AsemAlhaidary/hexo-search-generator#3]
You have both `<link>` and `<url>` set to the same value. Link should be the canonical pathway (`page.canonical_path`) that’s easy to read no matter the language. URL should be the escaped/encoded string - friendly to browsers (`page.path`). 

## Reference 
- https://support.google.com/webmasters/answer/10347851?hl=en
- https://www.shopify.com/partners/blog/canonical-urls

**Comment by AsemAlhaidary** [comment]
Okay 👍

**Comment by AsemAlhaidary** [comment]
https://github.com/lorezyra/Richie2.com/issues/224

**Comment by lorezyra** [comment]
Interesting that `page.path` and `post.path` are a bit different. When I looked through the `page` data for the pagination script, I could see `page.canonical_path`. That's why I suggested it.
